version: '3.9'
 
services:
  db:
    image: mysql:latest
    ports:
      - 3307:3306
    networks:
      - default_network
    environment:
      - MYSQL_ROOT_PASSWORD=ubuntu
      - MYSQL_DATABASE=devops_tp
      - MYSQL_USER=root
   
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      
      
networks:
  default_network:
   


